"""A tiny teaching-friendly visual programming wrapper around pygame-ce.

Typical use::

    import funground as f

    x = 50

    def setup():
        f.size(640, 400)

    def draw():
        global x
        f.background("white")
        f.circle(x, f.height / 2, 40)
        x += 2

    f.run()
"""

from . import api as _api
from .api import (
    Vector,
    apply_matrix,
    arc,
    background,
    begin_contour,
    begin_shape,
    bezier,
    bezier_point,
    bezier_tangent,
    bezier_vertex,
    blend_mode,
    circle,
    clear,
    clip,
    color,
    constrain,
    cursor,
    curve,
    curve_point,
    curve_tangent,
    curve_tightness,
    curve_vertex,
    day,
    degrees,
    distance,
    draw_path,
    ellipse,
    end_contour,
    end_shape,
    exit,
    fill,
    frame_rate,
    full_screen,
    hour,
    hsb,
    hsl,
    is_looping,
    key_down,
    lerp,
    lerp_color,
    line,
    linear_gradient,
    load_font,
    loop,
    mag,
    map_range,
    millis,
    minute,
    miter_limit,
    month,
    no_clip,
    no_cursor,
    no_dash,
    no_fill,
    no_loop,
    no_shadow,
    no_smooth,
    no_stroke,
    noise,
    noise_detail,
    noise_seed,
    norm,
    opacity,
    path,
    point,
    polygon,
    pop,
    push,
    quad,
    quadratic_vertex,
    radial_gradient,
    radians,
    random,
    random_choice,
    random_gaussian,
    random_seed,
    rect,
    redraw,
    reset_matrix,
    resize_canvas,
    rotate,
    run,
    save,
    save_frames,
    saved_state,
    scale,
    second,
    shadow,
    shear_x,
    shear_y,
    size,
    smooth,
    square,
    stop,
    stroke,
    stroke_cap,
    stroke_dash,
    stroke_join,
    stroke_width,
    text,
    text_align,
    text_ascent,
    text_box,
    text_descent,
    text_font,
    text_leading,
    text_size,
    text_style,
    text_width,
    translate,
    triangle,
    vertex,
    year,
)

__version__ = "0.1.0.dev0"

__all__ = [
    "Vector",
    "apply_matrix",
    "arc",
    "background",
    "begin_contour",
    "begin_shape",
    "bezier",
    "bezier_point",
    "bezier_tangent",
    "bezier_vertex",
    "blend_mode",
    "circle",
    "clear",
    "clip",
    "color",
    "constrain",
    "cursor",
    "curve",
    "curve_point",
    "curve_tangent",
    "curve_tightness",
    "curve_vertex",
    "day",
    "degrees",
    "distance",
    "draw_path",
    "ellipse",
    "end_contour",
    "end_shape",
    "exit",
    "fill",
    "frame_rate",
    "full_screen",
    "hour",
    "hsb",
    "hsl",
    "is_looping",
    "key_down",
    "lerp",
    "lerp_color",
    "line",
    "linear_gradient",
    "load_font",
    "loop",
    "mag",
    "map_range",
    "millis",
    "minute",
    "miter_limit",
    "month",
    "no_clip",
    "no_cursor",
    "no_dash",
    "no_fill",
    "no_loop",
    "no_shadow",
    "no_smooth",
    "no_stroke",
    "noise",
    "noise_detail",
    "noise_seed",
    "norm",
    "opacity",
    "path",
    "point",
    "polygon",
    "pop",
    "push",
    "quad",
    "quadratic_vertex",
    "radial_gradient",
    "radians",
    "random",
    "random_choice",
    "random_gaussian",
    "random_seed",
    "rect",
    "redraw",
    "reset_matrix",
    "resize_canvas",
    "rotate",
    "run",
    "save",
    "save_frames",
    "saved_state",
    "scale",
    "second",
    "shadow",
    "shear_x",
    "shear_y",
    "size",
    "smooth",
    "square",
    "stop",
    "stroke",
    "stroke_cap",
    "stroke_dash",
    "stroke_join",
    "stroke_width",
    "text",
    "text_align",
    "text_ascent",
    "text_box",
    "text_descent",
    "text_font",
    "text_leading",
    "text_size",
    "text_style",
    "text_width",
    "translate",
    "triangle",
    "vertex",
    "year",
    "width",
    "height",
    "mouse_x",
    "mouse_y",
    "is_mouse_pressed",
    "pmouse_x",
    "pmouse_y",
    "mouse_button",
    "key",
    "key_code",
    "is_key_pressed",
    "frame_count",
    "delta_time",
]


# D-016: v0.5's live value mouse_pressed became is_mouse_pressed, because mouse_pressed() is
# now the name of the callback (as in p5). The old name fails with a pointer to the new one.
_RENAMED = {
    "mouse_pressed": "f.mouse_pressed was renamed to f.is_mouse_pressed (True while a mouse button is "
                     "held). To react to a click, define a function called mouse_pressed() in your sketch.",
}


def __getattr__(name: str):
    """Expose live values without copying stale integers into this module."""
    if name in _api.LIVE_NAMES:
        return _api.live_value(name)
    if name in _RENAMED:
        raise AttributeError(_RENAMED[name])
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
