"""A tiny teaching-friendly visual programming wrapper around pygame-ce.

Typical use::

    import playground as p

    x = 50

    def setup():
        p.size(640, 400)

    def draw():
        global x
        p.background("white")
        p.circle(x, p.height / 2, 40)
        x += 2

    p.run()
"""

from . import api as _api
from .api import (
    apply_matrix,
    arc,
    background,
    begin_contour,
    begin_shape,
    bezier,
    bezier_point,
    bezier_tangent,
    bezier_vertex,
    circle,
    clear,
    clip,
    constrain,
    curve,
    curve_point,
    curve_tangent,
    curve_tightness,
    curve_vertex,
    degrees,
    distance,
    draw_path,
    ellipse,
    end_contour,
    end_shape,
    fill,
    key_down,
    lerp,
    line,
    mag,
    map_range,
    miter_limit,
    no_clip,
    no_dash,
    no_fill,
    no_smooth,
    no_stroke,
    noise,
    noise_detail,
    noise_seed,
    norm,
    path,
    point,
    polygon,
    pop,
    push,
    quad,
    quadratic_vertex,
    radians,
    random,
    random_choice,
    random_gaussian,
    random_seed,
    rect,
    reset_matrix,
    rotate,
    run,
    save,
    saved_state,
    scale,
    shear_x,
    shear_y,
    size,
    smooth,
    square,
    stop,
    stroke,
    stroke_cap,
    stroke_dash,
    stroke_join,
    stroke_width,
    text,
    text_size,
    text_width,
    translate,
    triangle,
    vertex,
)

__version__ = "0.7.0.dev0"

__all__ = [
    "apply_matrix",
    "arc",
    "background",
    "begin_contour",
    "begin_shape",
    "bezier",
    "bezier_point",
    "bezier_tangent",
    "bezier_vertex",
    "circle",
    "clear",
    "clip",
    "constrain",
    "curve",
    "curve_point",
    "curve_tangent",
    "curve_tightness",
    "curve_vertex",
    "degrees",
    "distance",
    "draw_path",
    "ellipse",
    "end_contour",
    "end_shape",
    "fill",
    "key_down",
    "lerp",
    "line",
    "mag",
    "map_range",
    "miter_limit",
    "no_clip",
    "no_dash",
    "no_fill",
    "no_smooth",
    "no_stroke",
    "noise",
    "noise_detail",
    "noise_seed",
    "norm",
    "path",
    "point",
    "polygon",
    "pop",
    "push",
    "quad",
    "quadratic_vertex",
    "radians",
    "random",
    "random_choice",
    "random_gaussian",
    "random_seed",
    "rect",
    "reset_matrix",
    "rotate",
    "run",
    "save",
    "saved_state",
    "scale",
    "shear_x",
    "shear_y",
    "size",
    "smooth",
    "square",
    "stop",
    "stroke",
    "stroke_cap",
    "stroke_dash",
    "stroke_join",
    "stroke_width",
    "text",
    "text_size",
    "text_width",
    "translate",
    "triangle",
    "vertex",
    "width",
    "height",
    "mouse_x",
    "mouse_y",
    "mouse_pressed",
    "frame_count",
    "delta_time",
]


def __getattr__(name: str):
    """Expose live values without copying stale integers into this module."""
    if name in _api.LIVE_NAMES:
        return _api.live_value(name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
